# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 16:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('courses', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
